export const CREATE_TOKEN_LOADING = 'CREATE_TOKEN_LOADING';
export const CREATE_TOKEN_FAILED = 'CREATE_TOKEN_FAILED';
export const CREATE_TOKEN_SUCCESS = 'CREATE_TOKEN_SUCCESS';

export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const SIGNIN_LOADING = 'SIGNIN_LOADING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';

export const AUTHENTICATED = 'AUTHENTICATED';
export const SIGN_OUT = 'SIGN_OUT';

export const LOAD_USER ='LOAD_USER';


export const HAVE_STRIPE = 'HAVE_STRIPE';


export const SELECT_CARD = 'SELECT_CARD';

