export const CREATE_TOKEN_LOADING = 'CREATE_TOKEN_LOADING';
export const CREATE_TOKEN_FAILED = 'CREATE_TOKEN_FAILED';
export const CREATE_TOKEN_SUCCESS = 'CREATE_TOKEN_SUCCESS';

export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const SIGNIN_LOADING = 'SIGNIN_LOADING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';

export const AUTHENTICATED = 'AUTHENTICATED';
export const SIGN_OUT = 'SIGN_OUT';

export const LOAD_USER ='LOAD_USER';


export const HAVE_STRIPE = 'HAVE_STRIPE';


export const SELECT_CARD = 'SELECT_CARD';

export const SELECT_COIN = 'SELECT_COIN';
export const SELECT_NODE_QUANTITY = 'SELECT_NODE_QUANTITY'

export const GENERATE_TRANSACTION_LOADING ='GENERATE_TRANSACTION_LOADING'
export const GENERATE_TRANSACTION_SUCCESS ='GENERATE_TRANSACTION_SUCCESS'
export const GENERATE_TRANSACTION_FAILED ='GENERATE_TRANSACTION_FAILED'

export const GET_INPUT_COIN = 'GET_INPUT_COIN'
export const GET_OUTPUT_COIN = 'GET_OUTPUT_COIN'
export const GET_INPUT_AMOUNT = 'GET_INPUT_AMOUNT'
export const GET_WALLET_ADDRESS = 'GET_WALLET_ADDRESS'

export const FETCH_ESTIMATED_OUTPUT= 'FETCH_ESTIMATED_OUTPUT'

export const FETCH_ACTIVATION_LOADING = 'FETCH_ACTIVATION_LOADING'
export const FETCH_ACTIVATION_SUCCESS = 'FETCH_ACTIVATION_SUCCESS'
export const FETCH_ACTIVATION_SUCCESS_NOT_FOUND = 'FETCH_ACTIVATION_SUCCESS_NOT_FOUND'
export const FETCH_ACTIVATION_FAIL = 'FETCH_ACTIVATION_FAIL'

export const FETCH_EXSTATS_LOADING = 'FETCH_EXSTATS_LOADING'//EXSTATS = exchange status
export const FETCH_EXSTATS_SUCCESS = 'FETCH_EXSTATS_SUCCESS'
export const FETCH_EXSTATS_FAIL = 'FETCH_EXSTATS_FAIL'

export const FETCH_ORDERS_LOADING = 'FETCH_ORDERS_LOADING'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'
